### ISSUE TITLE
v2.26.0 not published to Marketplace?

### ISSUE THREAD

**Issue by mrienstra** [streetsidesoftware/cspell-action#1243]
Hi! Just noticed [GitHub Marketplace](https://github.com/marketplace/actions/cspell-action) shows v2.25.0 as the latest, even though [v2.26.00](https://github.com/streetsidesoftware/cspell-action/releases/tag/v2.26.0) was released March 27th.

Might be a fluke one-off problem, not clear to me yet how this repo is setup to publish.

**Comment by Jason3S** [comment]
@mrienstra,

The release to GitHub Marketplace requires a second step that hasn't been fully automated.

**Comment by mrienstra** [comment]
Thanks @Jason3S!

Not sure if it'll go anywhere, but I started a new conversation here: https://github.com/orgs/community/discussions/52135

Closing this as it sounds like there's not clear path toward further automation at this time, and the Marketplace is current again.
