### ISSUE TITLE
Support suggestions (`--show-suggestions`) for words added via `flagWords`

### ISSUE THREAD

**Issue by klonos** [streetsidesoftware/cspell-action#1455]
## Problem summary
Words added via `flagWords` are detected as "unknown word" and there is no suggestions despite having configured some in the settings file.

## Details
As per https://streetsidesoftware.com/vscode-spell-checker/docs/configuration/#cspellflagwords, we have the following configured in the `cspell.json` GHA configuration file for our project:
```json
  "flagWords": [
    "blacklist: denylist, deny list, deny, block, denied list, blocked list",
    "blacklisted: disallowed, denied, blocked",
    "blacklisting: disallowing, denying, blocking",
    "master: primary, main, active, default, base",
    "slave: secondary, replica, standby, fallback",
    "webmaster: admin, administrator",
    "whitelist: allowlist, allow list, allow, allowed list",
    "whitelisted: allowed",
    "whitelisting: allowing"
  ],
```

However, this is the output:
<img src="https://github.com/backdrop/backdrop-issues/assets/2423362/b9d2b1c6-aa4e-46e9-8dac-371342512e85" width=50%>
<img src="https://github.com/backdrop/backdrop-issues/assets/2423362/5d9f51bf-f143-4949-8e10-60d2487872e5" width=30%>

As you can see, there are no suggestions, and the words are reported as "unknown" instead of "flagged".

**Comment by Jason3S** [comment]
@klonos,

You bring up a good point. That action reporting hasn't been updated since the suggestion feature was added.
