### ISSUE TITLE
Glob starting or ending with ' (single quote) is not likely to match any files: '.

### ISSUE THREAD

**Issue by fu050409** [streetsidesoftware/cspell-action#1837]
Hi! I'm using `cspell-action` in my repository, the workflows worked properly but an error was thrown out unexpectedly:

![image](https://github.com/streetsidesoftware/cspell-action/assets/46275354/6ebf4533-4847-4f7b-8603-64f0ba457dd2)

My Workflow: https://github.com/fu050409/rshotkey/actions/runs/9824775212/workflow?pr=13

I dont know what happened, it checked my workflow file (above) and didnt found any issue.

**Comment by fu050409** [comment]
Any response will be appreciated

**Comment by Jason3S** [comment]
@fu050409,

Please consider upgrading to v6.
https://github.com/fu050409/rshotkey/blob/1a1259e3f495c5cb7110855f08323ba7e7ad3bb1/.github/workflows/cspell.yml#L17

**Comment by fu050409** [comment]
> @fu050409,
> 
> Please consider upgrading to v6. https://github.com/fu050409/rshotkey/blob/1a1259e3f495c5cb7110855f08323ba7e7ad3bb1/.github/workflows/cspell.yml#L17

Thanks a lot! This is really caused by my carelessness :)
