### ISSUE TITLE
Action reports success despite config load error

### ISSUE THREAD

**Issue by chalin** [streetsidesoftware/cspell-action#1897]
CSpell-action reported as succeeding

> [SPELLING check](https://github.com/open-telemetry/opentelemetry.io/actions/runs/10315596580/job/28556087229#logs)
> _succeeded 4 hours ago in 5s_

despite a configuration error (from https://github.com/open-telemetry/opentelemetry.io/actions/runs/10317103275/job/28560650923):

<pre>
Run streetsidesoftware/cspell-action@v6
cspell-action
Pull Request
<b>Error: Configuration
        name: Configuration Loader Error
        msg: Failed to resolve configuration file: "@cspell/dict-es-es/cspell-ext.json" referenced from "./.cspell.yml"</b>
</pre>

/cc @open-telemetry/docs-maintainers @svnm @theletterf

**Comment by Jason3S** [comment]
@chalin,

Thank you. I agree, it should fail if there are configuration errors.
