### ISSUE TITLE
Accept a Parameter That Allows Action to Run On All Files

### ISSUE THREAD

**Issue by Kurt-von-Laven** [streetsidesoftware/cspell-action#213]
Presently, the action only runs on modified files, which is a great default, but for a small or young code base, it would be ideal to be able to address all spelling issues in one shot rather than be intermittently nagged. On large or old code bases, in conjunction with similar summaries from other static analysis tools, this feature would also support quantifying technical debt for planning, tracking, and decision-making purposes. (Obviously, one might run the tool locally in the meantime.)

**Comment by Jason3S** [comment]
I agree that this could be useful. In some cases it might be faster since it won't need to download the changes.

**Comment by Jason3S** [comment]
This should be fixed with  Release 1.2.1
