### ISSUE TITLE
Offer v1 tags too

### ISSUE THREAD

**Issue by XhmikosR** [streetsidesoftware/cspell-action#523]
@Jason3S  Hello!

Could you also publish the major/minor tags on each release too? That way it should be possible to use `streetsidesoftware/cspell-action@v1` without the need to bump the action on each minor/patch release.

Thanks!

**Comment by Jason3S** [comment]
@XhmikosR,

I'll take a look.

**Comment by XhmikosR** [comment]
That was fast, thanks!
